### ISSUE TITLE
Why is the interface in a separate repo?

### ISSUE THREAD

**Issue by shadowhand** [auraphp/Aura.Payload#1]
It's weird to me that the PayloadInterface is in a separate repository. If someone wanted to use the interface, they could do so without using the implemented class. The usability of the current interface is also questionable, since it uses a weird namespace.

I think Payload and PayloadInterface should be merged into a single repository.

**Comment by pmjones** [comment]
/me nods

Splitting the interface from the implementation is admittedly experimental. It seems to me that others may wish to implement the interface without the "overhead" of the default Aura implementation. (Yes, the default implementation is a single class, so "overhead" is an exaggeration for effect.)

Having said that, it may be that this is so minimal a case that having them together would not be a big deal in terms of "overhead" for even the most dependency-sensitive developer, and that the separate-packages-for-interface-and-implementation experiment would be better elsewhere.

Further thoughts?

**Comment by shadowhand** [comment]
> It seems to me that others may wish to implement the interface without the "overhead" of the default Aura implementation.

That's already possible, as a developer to choose not to use the default implementation. I think having them together in one repo reduces the cognitive overhead, because it allows the developer to look at them side-by-side (in the filesystem).

**Comment by pmjones** [comment]
> That's already possible, as a developer to choose not to use the default implementation.

But then he's stuck downloading code he's not using. (I know, it's just one file; I'm addressing the principle here. ;-)

> having them together in one repo reduces the cognitive overhead

(/me nods) Agreed. Like I said, this is mostly an experiment to see how well it works in a small case, before I move on to a larger case. It'll be easy in future to combine the two packages if it turns out to be unwise to deliver them separately (and before a 1.0 stable, obviously).

**Comment by shadowhand** [comment]
@pmjones _if_ there were external dependencies that would be pulled in, I would consider that a problem. But I don't think code splitting just for the sake of splitting is useful.

**Comment by shadowhand** [comment]
At risk of getting off topic... I'd also like to discuss ADR interop with you, as we (@wheniwork) have been working on a framework that we're calling @sparkphp/spark, which is largely motivated by Radar, but with different dependencies. I would very much like to collaborate on the core interfaces of your ADR pattern, so I've developed a separate package @sparkphp/adr which aims to provide interfaces and traits that help implement ADR. I'm interested to hear your thoughts on the interfaces and how we could develop an "ADR core" that depends solely on PSR-7 and makes no assumptions about routing, dependency injection, etc.

**Comment by pmjones** [comment]
> I'm interested to hear your thoughts on the interfaces and how we could develop an "ADR core" that depends solely on PSR-7 and makes no assumptions about routing, dependency injection, etc.

This sounds _very_ interesting to me. I think the [midwrap](https://github.com/radarphp/Radar.Adr/tree/midwrap) branch of Radar.Ad goes a long way toward that. The routing/action/sending handlers have been extracted entirely, and the only dependency between them is the route (from routing to action) along with request/response (obviously).

@NigelGreenway has set up an ADR google group at https://groups.google.com/forum/#!forum/action-domain-responder that might be a good discussion location for this.

**Comment by shadowhand** [comment]
@pmjones thanks! I've continued the discussion here https://groups.google.com/forum/#!topic/action-domain-responder/HucHUYDXPZQ

**Comment by pmjones** [comment]
Closing this ticket as a result of the ensuing discussion. If it's still a problem, let me know.
