### ISSUE TITLE
Mutable?

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Payload#12]
Was there ever any discussion on mutability?

I see that [equips payload is immutable](https://github.com/equip/framework/blob/master/src/Payload.php), and thought I remembered some discussion around the matter, but now that I'm looking, I don't see it.

Was immutability consciously rejected for a reason?

**Comment by pmjones** [comment]
I don't recall it coming up before 1.0 stable, but my recollection may be faulty.

In any case, IMO a generic payload is probably best only as a "starter" payload; your domain is probably better off defining a payload class (or series of payload classes) of its own.

Do you get where I'm coming from?

**Comment by pmjones** [comment]
It appears that true immutability is really difficult to implement. Any object dumped into the input or output arrays, for example, cannot be guaranteed to be unchanging. That alone makes immutability impossible for the Payload to guarantee.
