### ISSUE TITLE
What does a redirect response look like?

### ISSUE THREAD

**Issue by shadowhand** [auraphp/Aura.Payload#5]
How do we create a payload that redirects to another location? I don't see anything in the current statuses that would be semantically correct.

**Comment by shadowhand** [comment]
cc @bvisness

**Comment by pmjones** [comment]
Technically, the Payload status types are not HTTP status types. They are domain-specific, not UI-specific, so the user interface is in charge of determining what to do with each payload based on its status. (The HTTP-type status and Payload status do map well to each other for a lot of cases, though.)

If you're talking about a GET-after-POST situation, e.g. to redirect to updated content after editing, I imagine all that's needed is a "success" or "updated" type of status. An Update-specific Responder would then specify a redirect to the URL for the ID of the edited content.

Does that help at all?

**Comment by pmjones** [comment]
Also, if you need it, it's perfectly reasonable to create your own Payload statuses specific to your domain. I'd expect different domains to have different statuses specific to them; the ones with the Payload package are generic.

**Comment by shadowhand** [comment]
Ah ha, rubber duck moment. The use case had to do with checking if a user is logged in, which is a `NOT_AUTHENTICATED` status. We just need a custom responder to does a redirect instead of a 401 status.

Thanks!

**Comment by pmjones** [comment]
Quack quack. :-)
